spring.application.name=spring-singleflight
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=testdbuser
spring.datasource.password=testdbuser
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG
management.endpoints.web.exposure.include=health,info,metrics
server.port=9010